# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: YourPalRyan
email: RMParsley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a developer with a background in design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourpalryan.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: ryanparsley
twitter_username: ryanparsley
github_username:  ryanparsley

# Build settings
markdown: kramdown

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

include: ["_pages"]

paginate: 5 # amount of posts to show
paginate_path: /page:num/

collections:
  tangents:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _tangents
  - scope:
      path: ""
      type: tangents
    values:
      layout: single
      author_profile: true
      share: true

author:
  name   : "Ryan Parsley"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I’m a developer with a background in design."
  email  : # optional
  uri    : "http://ryanparsley.com"
  twitter: "ryanparsley"
  github : "ryanparsley"
  codepen: "ryanparsley"

social:
  links:
    - "https://twitter.com/ryanparsley"
    - "https://facebook.com/RyanParsley"
    - "https://instagram.com/ryanparsley"
    - "https://www.linkedin.com/in/ryanparsley"
    - "https://plus.google.com/u/0/+RyanParsleydotcom"

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-474703-2"

search: true
